Add Key "PropType"
R1KO/Gifts pull request #3
Opened 2019-09-18 12:39 UTC by DarklSide

Для некоторых моделей для их создания нужен не только "prop_physics_override".

Пример:
```php
"подарок 4"
{
	"PropType"			"prop_dynamic_override"
	"Model"				"models/props_fairgrounds/giraffe.mdl"

	"Chance"			"20"
	"Lifetime"			"10.0"

	"TextToAll"			"#B8860B{NAME} #FFFF00поднял подарок и получит #FFA500Бонус!"
	"TextToPlayer"		"#FFFF00Вы подняли подарок\nи получите #FFA500Бонус!"
}
```

2019-09-18 13:22 UTC, R1KO requested changes

2019-09-18 13:22 UTC, R1KO commented on addons/sourcemod/scripting/Gifts_Core.sp
> +	if (StrEqual(sBuffer, "prop_physics_override") || StrEqual(sBuffer, "prop_dynamic_override") || StrEqual(sBuffer, "prop_physics_multiplayer") || StrEqual(sBuffer, "prop_dynamic") || StrEqual(sBuffer
Сделай проверку через отдельный метод циклом.

Еще можно валидацию вынести в цикл в ините, где мы звуки и модели загружаем, там же сделать и валидацию типа и его исправление в kv, а потом просто брать его из кв уже валидным.

2019-09-18 16:43 UTC, DarklSide commented on addons/sourcemod/scripting/Gifts_Core.sp
> +	if (StrEqual(sBuffer, "prop_physics_override") || StrEqual(sBuffer, "prop_dynamic_override") || StrEqual(sBuffer, "prop_physics_multiplayer") || StrEqual(sBuffer, "prop_dynamic") || StrEqual(sBuffer
> а потом просто брать его из кв уже валидным.

В кастомном kv все равно нужно делать проверку "PropType".

2019-09-19 09:30 UTC, R1KO approved these changes

2019-09-19 09:30 UTC, merged